import React, { useEffect, useRef, useState } from "react";
import "../../styles/privacyPolicy.css";
import "locomotive-scroll/locomotive-scroll.css";

import { IoMdClose } from "react-icons/io";

function PrivacyPolicy({ show, setShow }) {
  const [isOpen, setIsOpen] = useState(false);
  const containerRef = useRef(null);
  useEffect(() => {
    if (isOpen) {
      function handleClickOutside(event) {
        if (
          containerRef.current &&
          !containerRef.current.contains(event.target)
        ) {
          console.log(true);
          setShow(false);
        }
      }

      document.addEventListener("click", handleClickOutside);

      return () => {
        document.removeEventListener("click", handleClickOutside);
      };
    }
  }, [isOpen]);

  useEffect(() => {
    setIsOpen(show);
  }, [show]);

  return (
    <div id="privacyPolicy" className={`privacyPolicy ${show ? "show" : ""}`}>
      <div ref={containerRef} className="container">
        <div className="header">
          <div className="title">
            <p className="label">PRIVACY AND POLICY</p>
            <p className="date">Updated at March 15th, 2024</p>
          </div>
          <div className="action">
            <IoMdClose onClick={() => setShow(false)} />
          </div>
        </div>
        <div className="content ignore-scroll">
          <p className="paragraph">
            Go Genesis Solar Power (“we,” “our,” or “us”) is committed to
            protecting your privacy. This Privacy Policy explains how your
            personal information is collected, used, and disclosed by Go Genesis
            Solar Power
          </p>

          <p className="paragraph">
            This Privacy Policy applies to our website, and its associated
            subdomains (collectively, our “Service”) alongside our application,
            Go Genesis Solar Power. By accessing or using our Service, you
            signify that you have read, understood, and agree to our collection,
            storage, use, and disclosure of your personal information as
            described in this Privacy Policy and our Terms of Service.
          </p>

          <div className="title-desc">
            <p className="title">Definitions and key terms</p>
            <p className="desc">
              To help explain things as clearly as possible in this Privacy
              Policy, every time any of these terms are referenced, are strictly
              defined as:
            </p>
          </div>

          <ul>
            <li>
              Cookie: small amount of data generated by a website and saved by
              your web browser. It is used to identify your browser, provide
              analytics, remember information about you such as your language
              preference or login information.
            </li>
            <li>
              Company: when this policy mentions “Company,” “we,” “us,” or
              “our,” it refers to Go Genesis Solar Power, (6028 Stonybook CT,
              Topeka, KS 66614), that is responsible for your information under
              this Privacy Policy.
            </li>
            <li>
              Country: where Go Genesis Solar Power or the owners/founders of Go
              Genesis Solar Power are based, in this case is United States of
              America.
            </li>
            <li>
              Cookie: small amount of data generated by a website and saved by
              your web browser. It is used to identify your browser, provide
              analytics, remember information about you such as your language
              preference or login information.
            </li>
            <li>
              Company: when this policy mentions “Company,” “we,” “us,” or
              “our,” it refers to Go Genesis Solar Power, (6028 Stonybook CT,
              Topeka, KS 66614), that is responsible for your information under
              this Privacy Policy.
            </li>
            <li>
              Country: where Go Genesis Solar Power or the owners/founders of Go
              Genesis Solar Power are based, in this case is United States of
              America.
            </li>
            <li>
              Cookie: small amount of data generated by a website and saved by
              your web browser. It is used to identify your browser, provide
              analytics, remember information about you such as your language
              preference or login information.
            </li>
            <li>
              Company: when this policy mentions “Company,” “we,” “us,” or
              “our,” it refers to Go Genesis Solar Power, (6028 Stonybook CT,
              Topeka, KS 66614), that is responsible for your information under
              this Privacy Policy.
            </li>
            <li>
              Country: where Go Genesis Solar Power or the owners/founders of Go
              Genesis Solar Power are based, in this case is United States of
              America.
            </li>
            <li>
              Cookie: small amount of data generated by a website and saved by
              your web browser. It is used to identify your browser, provide
              analytics, remember information about you such as your language
              preference or login information.
            </li>
            <li>
              Company: when this policy mentions “Company,” “we,” “us,” or
              “our,” it refers to Go Genesis Solar Power, (6028 Stonybook CT,
              Topeka, KS 66614), that is responsible for your information under
              this Privacy Policy.
            </li>
            <li>
              Country: where Go Genesis Solar Power or the owners/founders of Go
              Genesis Solar Power are based, in this case is United States of
              America.
            </li>
            <li>
              Cookie: small amount of data generated by a website and saved by
              your web browser. It is used to identify your browser, provide
              analytics, remember information about you such as your language
              preference or login information.
            </li>
            <li>
              Company: when this policy mentions “Company,” “we,” “us,” or
              “our,” it refers to Go Genesis Solar Power, (6028 Stonybook CT,
              Topeka, KS 66614), that is responsible for your information under
              this Privacy Policy.
            </li>
            <li>
              Country: where Go Genesis Solar Power or the owners/founders of Go
              Genesis Solar Power are based, in this case is United States of
              America.
            </li>
          </ul>
        </div>
        <div className="action">
          <button onClick={() => setShow(false)}>I Understand</button>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicy;
